# Generated by Django 5.2.15 on 2026-08-12 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('fausse_annonce', 'Fausse annonce'), ('deja_loue', 'Déjà loué'), ('contenu_inapproprie', 'Contenu inapproprié'), ('autre', 'Autre')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ouvert', 'Ouvert'), ('traite', 'Traité'), ('rejete', 'Rejeté')], default='ouvert', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='listings.listing')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
