# Generated by Django 5.2.15 on 2026-08-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'amenities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('neighborhood', models.CharField(help_text='Quartier de Yaoundé', max_length=100)),
                ('property_type', models.CharField(choices=[('studio', 'Studio'), ('appartement', 'Appartement'), ('chambre', 'Chambre'), ('villa', 'Villa')], max_length=20)),
                ('rent_amount', models.PositiveIntegerField(help_text='FCFA / mois')),
                ('deposit_amount', models.PositiveIntegerField(default=0, help_text='FCFA')),
                ('terms', models.TextField(blank=True, help_text='Modalités')),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('publiee', 'Publiée'), ('rejetee', 'Rejetée'), ('louee', 'Louée'), ('expiree', 'Expirée')], default='en_attente', max_length=20)),
                ('source', models.CharField(choices=[('annonceur', 'Annonceur'), ('amorce', 'Amorçage')], default='annonceur', max_length=20)),
                ('verified', models.BooleanField(default=False, help_text='Badge « Vérifié Bailconnect »')),
                ('seed_contact_name', models.CharField(blank=True, max_length=150)),
                ('seed_contact_phone', models.CharField(blank=True, max_length=20)),
                ('last_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Vidéo')], max_length=10)),
                ('file', models.FileField(upload_to='listings/%Y/%m/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('duration_seconds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'listing media',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
