# Generated by Django 5.2.15 on 2026-09-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('publiee', 'Publiée'), ('rejetee', 'Rejetée'), ('louee', 'Louée'), ('expiree', 'Expirée'), ('archivee', 'Archivée')], default='en_attente', max_length=20),
        ),
    ]
