# Generated by Django 5.2.15 on 2026-08-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
