# Generated by Django 5.2.15 on 2026-09-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='appointment_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='appointment_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
