# Generated by Django 5.2.15 on 2026-08-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_otpcode_phone_number_otpcode_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_annonceur',
            field=models.BooleanField(default=False, help_text="Capacité de gérer des annonces — un compte locataire peut aussi l'acquérir (ex. amorçage)."),
        ),
    ]
