# Generated by Django 5.2.15 on 2026-08-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_annonceur'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='annonceur_type',
            field=models.CharField(blank=True, choices=[('bailleur', 'Bailleur'), ('agent', 'Agent')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, help_text='Ville/quartier — locataire uniquement.', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Contact WhatsApp des annonces — annonceur uniquement.', max_length=20),
        ),
    ]
