# Generated by Django 5.2.15 on 2026-08-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_annonceur_type_user_city_user_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='login_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
