# Generated by Django 5.2.15 on 2026-09-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_login_failed_attempts_user_login_locked_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Compte archivé par un admin (terminal, sans suppression des données) — implique is_active=False.'),
        ),
    ]
